---
title: "This is a Test"
# author: "Amber Camp"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    theme: 
      bootswatch: yeti
    source_code: embed
    navbar:
      - { title: "Amber Camp", href: "https://abcamp.github.io", align: right }
      - { icon: "fa fa-github", href: "https://github.com/abcamp", align: right, target: blank }
favicon: media/fav.png
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
```

# Page 1
## Row 

### Summary

This is an example of a dashboard with two pages.

Here is a second line of text.

## Row

### Chart A

TEST

```{r}
ggplot(diamonds, aes(x = carat, y = price)) +
  geom_point(alpha=0.1, size=1)
```

### Chart B

```{r}
diamonds %>%
  mutate(color = fct_rev(color)) %>% 
  ggplot(aes(x = color, y = price, color = color)) +
  geom_boxplot()
```

## Row {.tabset .tabset-fade data-height="400"}

### Chart C

```{r}
ggplot(diamonds, aes(x = price)) + 
  geom_freqpoly(aes(color = cut), binwidth = 500, linewidth = 0.75)
```

### Chart D

This is some test text

```{r}
test <- ggplot(diamonds, aes(x = price, y = after_stat(density))) + 
  geom_freqpoly(aes(color = cut), binwidth = 500, linewidth = 0.75)

ggplotly(test)
```

# Page 2

## Row

### Chart E

```{r}
knitr::kable(mpg)
```
