---
title: "CS201 Flexdashboard Practice"
# author: "Amber Camp"
# date: 11/18/24
output: 
  flexdashboard::flex_dashboard:
    orientation: columns # can also be rows
    vertical_layout: fill # can also be scroll
    source_code: embed
    theme:
      bootswatch: yeti
    navbar:
      - { title: "Amber Camp", href: "https://abcamp.github.io", align: right }
      - { icon: "fa fa-github", href: "https://github.com/abcamp", align: right, target: blank }
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
```


Column {data-width=350}
-----------------------------------------------------------------------

### Star Wars character heights by name

```{r}
ggplot(starwars, aes(x=name, y=height)) +
  geom_bar(stat="identity") +
  coord_flip()
```

### Count of Star Wars characters' homeworld by gender

```{r}
p <- ggplot(starwars, aes(x=homeworld, fill=gender)) +
  geom_bar()

ggplotly(p)
```

Column {data-width=650}
-----------------------------------------------------------------------
### Star Wars data table

```{r}
starwars <- starwars %>% 
  select(name, height, mass, gender, species, homeworld)

knitr::kable(starwars)
```

