---
title: "CS201 Flexdashboard Practice"
# author: "Amber Camp"
# date: 11/18/24
output: 
  flexdashboard::flex_dashboard:
    orientation: columns # can also be rows
    vertical_layout: scroll # can also be scroll
    source_code: embed
    theme:
      bootswatch: yeti
    navbar:
      - { title: "Amber Camp", href: "https://abcamp.github.io", align: right }
      - { icon: "fa fa-github", href: "https://github.com/abcamp", align: right, target: blank }
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
library(janitor)
library(here)
```


Column {data-width=350}
-----------------------------------------------------------------------

### Star Wars character heights by name

```{r}
ggplot(starwars, aes(x=name, y=height)) +
  geom_bar(stat="identity") +
  coord_flip()
```

### Count of Star Wars characters' homeworld by gender

```{r}
p <- ggplot(starwars, aes(x=homeworld, fill=gender)) +
  geom_bar()

ggplotly(p)
```

Column {data-width=650}
-----------------------------------------------------------------------
### Star Wars data table

```{r}
starwars <- starwars %>% 
  select(name, height, mass, gender, species, homeworld)

knitr::kable(starwars)
```

### Hello!
```{r}
flowerdata <- read_csv(here("data/flowers.csv"))

flowerdata <- flowerdata %>% clean_names()

color_climate_summary <- flowerdata %>%
  group_by(color, climate) %>%
  tally() %>%
  arrange(color, desc(n))

color_climate_plot <- ggplot(color_climate_summary, aes(x = color, y = n, fill = climate)) +
  geom_bar(stat = "identity") +
  labs(title = "Flower Color Distribution by Climate",
       x = "Color",
       y = "Count of Flowers",
       fill = "Climate") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))

interactive_color_climate_plot <- ggplotly(color_climate_plot)
interactive_color_climate_plot
```

